### ISSUE TITLE
跑图的时候闪退，并且提示错误报告，后面就一直进不去，并且显示错误报告

### ISSUE THREAD

**Issue by 18375674690** [PIPILAN/Parasites-Blood-Dawn#10]
### 是否有增添模组或者修改配置文件？ (Are there any modules added or configuration files modified?)

否

### 整合包版本 (Modpack Version)

1.0.5

### Java

Java8 64位

### 崩溃报告 (Crash Report)

[错误报告-2022-6-13_21.18.43.zip](https://github.com/PIPILAN/Parasites-Blood-Dawn/files/8899306/-2022-6-13_21.18.43.zip)

### 问题描述 (Bug Description)

玩了一会儿突然停顿，然后就闪退并出现错误报告，等重新登录，进入刚才闪退的图，虽然里面显示地形加载中，但是加载完立马闪退，显示错误报告。

**Comment by PIPILAN** [comment]
> 

错误报告无法查看，可以考虑直接黏贴进来或者使用pastebin等类型网站黏贴后，把网页发出来

**Comment by 18375674690** [comment]
[错误报告-2022-6-13_21.18.43.zip](https://github.com/PIPILAN/Parasites-Blood-Dawn/files/8900614/-2022-6-13_21.18.43.zip)

**Comment by PIPILAN** [comment]
> [错误报告-2022-6-13_21.18.43.zip](https://github.com/PIPILAN/Parasites-Blood-Dawn/files/8900614/-2022-6-13_21.18.43.zip)

确定是群内的1.0.5版本？不是1.0.4.2版本？游戏主界面左下角有写

**Comment by PIPILAN** [comment]
#7
