### ISSUE TITLE
服务器运行，突然报错

### ISSUE THREAD

**Issue by LVQAQ-cd** [PIPILAN/Parasites-Blood-Dawn#11]
### 是否有增添模组或者修改配置文件？ (Are there any modules added or configuration files modified?)

否

### 整合包版本 (Modpack Version)

1.0.4.2

### Java

8

### 崩溃报告 (Crash Report)

[crash-2022-06-16_15.18.31-server.zip](https://github.com/PIPILAN/Parasites-Blood-Dawn/files/8918055/crash-2022-06-16_15.18.31-server.zip)

### 问题描述 (Bug Description)

正常运行了一段时间后，输入/home命令后突然崩溃（也可能和这个命令无关）。重启服务器可以启动，但是任何账号进入服务器就会导致崩溃【此外，当改了某个按键后也导致了游戏奔溃（客户端），目前重置快捷键解决】

**Comment by PIPILAN** [comment]
首先，JAVA版本不是让你写8 11 17这种，是让你写到具体；其次，不建议使用墨端。最后， #7
