### ISSUE TITLE
关于我1.05崩溃了一直上不去，又修好了这件事。

### ISSUE THREAD

**Issue by gezi360520** [PIPILAN/Parasites-Blood-Dawn#12]
### 是否有增添模组或者修改配置文件？ (Are there any modules added or configuration files modified?)

否

### 整合包版本 (Modpack Version)

1.0.4.3

### Java

java833

### 崩溃报告 (Crash Report)

[错误报告-2022-6-13_23.11.06.zip](https://github.com/PIPILAN/Parasites-Blood-Dawn/files/8933116/-2022-6-13_23.11.06.zip)

### 问题描述 (Bug Description)

崩溃了然后一直上不去， 昨天晚上我群里聊天的时候，说开玩笑说我手里拿了土豆， 说不定是因为， 刚好腐烂导致一直崩溃， 然后我就吧food 食物保鲜的MOD， 关掉了， 我的存档就好了。今天还能正常玩。

**Comment by PIPILAN** [comment]
首先，整合包版本没有1.0.4.3，只有1.0.4.2。其次，非常感谢您的思路，我在foodfunk开源项目下发现了此报错，定位到模组问题，一直以来的问题终于找到了，感谢。
