### ISSUE TITLE
打开商店立即崩溃

### ISSUE THREAD

**Issue by Tipsd** [PIPILAN/Parasites-Blood-Dawn#14]
### 是否有增添模组或者修改配置文件？ (Are there any modules added or configuration files modified?)

否

### 整合包版本 (Modpack Version)

1.0.6

### Java

1.8.0_74

### 崩溃报告 (Crash Report)

[crash-2022-07-21_17.49.25-client.txt](https://github.com/PIPILAN/Parasites-Blood-Dawn/files/9158315/crash-2022-07-21_17.49.25-client.txt)

### 问题描述 (Bug Description)

**我用的是Mac系统**
右键进入商店（admit shop）就直接崩溃……

**Comment by PIPILAN** [comment]
首先，我建议你把java版本升级到8u333（这不是问题所在，只是看到了的建议）

你的问题同 #6

**Comment by Tipsd** [comment]
> 首先，我建议你把java版本升级到8u333（这不是问题所在，只是看到了的建议）
> 
> 你的问题同 #6

问题解决了，十分感谢！
（顺便夸一下整合包的优化，头一次体会到100+帧的感觉QWQ）
