### ISSUE TITLE
Linux系统运行服务端时发生错误崩溃

### ISSUE THREAD

**Issue by Wkuny** [PIPILAN/Parasites-Blood-Dawn#15]
### 反馈内容 (Content)

这是我Ubuntu Server( Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-46-generic x86_64) )上用Java 8运行服务端发生崩溃时产生的日志
[latest.log](https://github.com/PIPILAN/Parasites-Blood-Dawn/files/9315593/latest.log)
在Linux系统上从未能正常启动服务端
Java版本如下
openjdk version "1.8.0_342"
OpenJDK Runtime Environment (build 1.8.0_342-8u342-b07-0ubuntu1~22.04-b07)
OpenJDK 64-Bit Server VM (build 25.342-b07, mixed mode)

附：日志 [latest.log](https://github.com/PIPILAN/Parasites-Blood-Dawn/files/9315593/latest.log)

**Comment by PIPILAN** [comment]
初步来看是古代战争模组导致的内存溢出，请尝试分配更大内存

**Comment by Wkuny** [comment]
OK 我试试

**Comment by Wkuny** [comment]
OK 我分配了4500m就没事了
已经star你的这个项目了
