### ISSUE TITLE
游玩几分钟后游戏崩溃

### ISSUE THREAD

**Issue by kadungaoerji** [PIPILAN/Parasites-Blood-Dawn#16]
### 是否有增添模组或者修改配置文件？ (Are there any modules added or configuration files modified?)

是

### 整合包版本 (Modpack Version)

1.0.6

### Java

jre1.8.0_341

### 崩溃报告 (Crash Report)

[minecraft-exported-crash-info-2022-08-26T16-18-02.zip](https://github.com/PIPILAN/Parasites-Blood-Dawn/files/9431118/minecraft-exported-crash-info-2022-08-26T16-18-02.zip)

### 问题描述 (Bug Description)

进入游戏几分钟后就会崩溃

**Comment by PIPILAN** [comment]
这个问题很久了，之前已经减轻过出现的概率了，再出现我也不知道原因了
