### ISSUE TITLE
打开商店闪退

### ISSUE THREAD

**Issue by xianyup** [PIPILAN/Parasites-Blood-Dawn#18]
### 是否有增添模组或者修改配置文件？ (Are there any modules added or configuration files modified?)

否

### 整合包版本 (Modpack Version)

1.0.6

### Java

1.8.0_251

### 崩溃报告 (Crash Report)

[minecraft-exported-logs-2022-10-22T11-33-21.log](https://github.com/PIPILAN/Parasites-Blood-Dawn/files/9843512/minecraft-exported-logs-2022-10-22T11-33-21.log)

### 问题描述 (Bug Description)

一打开商店就闪退，提示正在关闭内置服务端

**Comment by PIPILAN** [comment]
#17
