### ISSUE TITLE
游戏崩溃

### ISSUE THREAD

**Issue by vase-ping** [PIPILAN/Parasites-Blood-Dawn#19]
### 是否有增添模组或者修改配置文件？ (Are there any modules added or configuration files modified?)

否

### 整合包版本 (Modpack Version)

1.1.0

### Java

jre8.0.51

### 崩溃报告 (Crash Report)

[错误报告-2023-2-24_20.37.47.zip](https://github.com/PIPILAN/Parasites-Blood-Dawn/files/10824130/-2023-2-24_20.37.47.zip)

### 问题描述 (Bug Description)

游戏中进行地图传送后，游戏崩溃

**Comment by PIPILAN** [comment]
1.1.1版本已修复
