### ISSUE TITLE
枪械Origin 12有装填bug

### ISSUE THREAD

**Issue by Nekrosyz** [PIPILAN/Parasites-Blood-Dawn#20]
### 是否有增添模组或者修改配置文件？ (Are there any modules added or configuration files modified?)

否

### 整合包版本 (Modpack Version)

1.1.0

### Java

8.0.321

### 问题描述 (Bug Description)

Origin12枪械在商店购买了对应弹夹后出现无法装填的情况，双击R键可以进行装填，但是打一枪弹夹就清空，并且弹夹也消失了，接着又开始无法装填

**Comment by PIPILAN** [comment]
维克枪械模组问题，本人无法复现也无力修复
