### ISSUE TITLE
PBD1.1.1的服务端问题

### ISSUE THREAD

**Issue by Crystalast029** [PIPILAN/Parasites-Blood-Dawn#21]
### 是否有增添模组或者修改配置文件？ (Are there any modules added or configuration files modified?)

否

### 整合包版本 (Modpack Version)

1.1.1

### Java

Azul Zulu 1.8.0_372

### 崩溃报告 (Crash Report)

[crash-2023-05-20_23.24.32-server.txt](https://github.com/PIPILAN/Parasites-Blood-Dawn/files/11522666/crash-2023-05-20_23.24.32-server.txt)

### 问题描述 (Bug Description)

在配置服务端之后，运行服务端一会就直接崩溃
1.1.0服务端则运行正常

**Comment by PIPILAN** [comment]
打包忘记移除部分客户端模组，简单直接的办法是删除服务端的fancymenu系列模组即可
