### ISSUE TITLE
1.1.1服务端启动失败

### ISSUE THREAD

**Issue by ZSKYYY** [PIPILAN/Parasites-Blood-Dawn#22]
### 是否有增添模组或者修改配置文件？ (Are there any modules added or configuration files modified?)

否

### 整合包版本 (Modpack Version)

1.1.1

### Java

build 1.8.0_281-b09

### 崩溃报告 (Crash Report)

[latest.log](https://github.com/PIPILAN/Parasites-Blood-Dawn/files/11578588/latest.log)

### 问题描述 (Bug Description)

按教程安装完forge写好run.bat启动就报错
用的Windows开服

**Comment by yhwsndbb** [comment]
我这也是历史版本也是一样

**Comment by PIPILAN** [comment]
https://github.com/PIPILAN/Parasites-Blood-Dawn/issues/21
