### ISSUE TITLE
开服务器报错

### ISSUE THREAD

**Issue by GFHK416** [PIPILAN/Parasites-Blood-Dawn#23]
### 是否有增添模组或者修改配置文件？ (Are there any modules added or configuration files modified?)

否

### 整合包版本 (Modpack Version)

1.1.1

### Java

1.8.0_181

### 崩溃报告 (Crash Report)

---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMCore (fancymenu_forge_2.14.7_MC_1.12-1.12.2.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  Quark Plugin (Quark-r1.6-179.jar)
  AppleCore (AppleCore-mc1.12.2-3.4.0.jar)
  ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  Moving Elevators Plugin (movingelevators-1.4.1-forge-mc1.12.jar)
  ChunkGenLimiterCoremod (chunkgenlimiter-1.1-core.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  JechCore (jecharacters-1.12.0-3.7.1.jar)
  SurgeLoadingPlugin (Surge-1.12.2-2.0.77.jar)
  KonkreteCore (konkrete_forge_1.6.0_MC_1.12-1.12.2.jar)
  MixinBooter (!mixinbooter-7.1.jar)
  MSICCoreMod (MyServerIsCompatible-1.12.2-1.0.jar)
  RandomPatches (randompatches-1.12.2-1.22.1.10.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  CreativePatchingLoader (CreativeCore_v1.10.70_mc1.12.2.jar)
  B3M_CorePlugin (B3M-1.12.2-17.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  CoreMod (MiniEffects-1.12.2-1.1.0.jar)
  weaponlib (mw3.0_sqr-0.7.21 BETA_mc1.12.2.jar)
  SuperMartijn642's Core Lib Plugin (supermartijn642corelib-1.1.7-forge-mc1.12.jar)
  CorePlugin (ForgeEndertech-1.12.2-4.5.6.1-build.0648.jar)
  MultiblockedLoadingPlugin (multiblocked-0.8.0.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 23-6-11 下午8:32
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/server/integrated/IntegratedServer
	at de.keksuccino.fancymenu.FancyMenu.getGameDirectory(FancyMenu.java:366)
	at de.keksuccino.fancymenu.FancyMenu.<clinit>(FancyMenu.java:64)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:539)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.integrated.IntegratedServer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 35 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@5f13be1 from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 37 more
Caused by: java.lang.RuntimeException: Attempted to load class chd for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
	... 39 more

(MixinBooter) Mixins in Stacktrace:
	net.minecraftforge.fml.common.LoadController:
		zone.rong.mixinbooter.mixin.LoadControllerMixin (mixin.mixinbooter.init.json)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 8597965888 bytes (8199 MB) / 10290200576 bytes (9813 MB) up to 10290200576 bytes (9813 MB)
	JVM Flags: 2 total; -Xmx10G -Xms10G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 106 mods loaded, 106 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                       | Version                   | Source                                                    | Signature                                |
	|:----- |:------------------------ |:------------------------- |:--------------------------------------------------------- |:---------------------------------------- |
	| LC    | minecraft                | 1.12.2                    | minecraft.jar                                             | None                                     |
	| LC    | mcp                      | 9.42                      | minecraft.jar                                             | None                                     |
	| LC    | FML                      | 8.0.99.99                 | forge-1.12.2-14.23.5.2860.jar                             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | forge                    | 14.23.5.2860              | forge-1.12.2-14.23.5.2860.jar                             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | creativecoredummy        | 1.0.0                     | minecraft.jar                                             | None                                     |
	| LC    | jecharacters             | 1.12.0-3.7.1              | jecharacters-1.12.0-3.7.1.jar                             | None                                     |
	| LC    | mixinbooter              | 7.1                       | minecraft.jar                                             | None                                     |
	| LC    | obfuscate                | 0.4.2                     | minecraft.jar                                             | None                                     |
	| LC    | randompatches            | 1.12.2-1.22.1.10          | randompatches-1.12.2-1.22.1.10.jar                        | None                                     |
	| LC    | forgeendertech           | 1.12.2-4.5.6.1            | ForgeEndertech-1.12.2-4.5.6.1-build.0648.jar              | None                                     |
	| LC    | adhooks                  | 1.12.2-3.3.1.0            | AdHooks-1.12.2-3.3.1.0-build.0626.jar                     | None                                     |
	| LC    | adminshop                | 1.0                       | adminshop-1.5.1.jar                                       | None                                     |
	| LC    | codechickenlib           | 3.2.3.358                 | CodeChickenLib-1.12.2-3.2.3.358-universal.jar             | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | ancientwarfare           | 1.12.2-2.7.0.1038         | ancientwarfare-1.12.2-2.7.0.1038.jar                      | None                                     |
	| LC    | redstoneflux             | 2.1.1                     | RedstoneFlux-1.12-2.1.1.1-universal.jar                   | None                                     |
	| LC    | ancientwarfareautomation | 1.12.2-2.7.0.1038         | ancientwarfare-1.12.2-2.7.0.1038.jar                      | None                                     |
	| LC    | ancientwarfarenpc        | 1.12.2-2.7.0.1038         | ancientwarfare-1.12.2-2.7.0.1038.jar                      | None                                     |
	| LC    | ancientwarfarestructure  | 1.12.2-2.7.0.1038         | ancientwarfare-1.12.2-2.7.0.1038.jar                      | None                                     |
	| LC    | ancientwarfarevehicle    | 1.12.2-2.7.0.1038         | ancientwarfare-1.12.2-2.7.0.1038.jar                      | None                                     |
	| LC    | applecore                | 3.4.0                     | AppleCore-mc1.12.2-3.4.0.jar                              | None                                     |
	| LC    | crafttweaker             | 4.1.20                    | CraftTweaker2-1.12-4.1.20.687.jar                         | None                                     |
	| LC    | mtlib                    | 3.0.7                     | MTLib-3.0.7.jar                                           | None                                     |
	| LC    | modtweaker               | 4.0.19                    | modtweaker-4.0.20.11.jar                                  | None                                     |
	| LC    | jei                      | 4.16.1.301                | jei_1.12.2-4.16.1.301.jar                                 | None                                     |
	| LC    | appleskin                | 1.0.14                    | AppleSkin-mc1.12-1.0.14.jar                               | None                                     |
	| LC    | attributefix             | 1.0.12                    | AttributeFix-Forge-1.12.2-1.0.12.jar                      | None                                     |
	| LC    | quark                    | r1.6-179                  | Quark-r1.6-179.jar                                        | None                                     |
	| LC    | autoreglib               | 1.3-32                    | AutoRegLib-1.3-32.jar                                     | None                                     |
	| LC    | B3M                      | 1.12.2-17                 | B3M-1.12.2-17.jar                                         | None                                     |
	| LC    | backstab                 | 1.0.3.2                   | backstab-1.12.2-1.0.3.2.jar                               | None                                     |
	| LC    | badmobs                  | 1.1.40                    | BadMobs-1.12.2-1.1.40.jar                                 | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | base                     | 3.14.0                    | base-1.12.2-3.14.0.jar                                    | None                                     |
	| LC    | bathappymod              | 2.0                       | BatHappyMod-1.12.2-2.1.jar                                | None                                     |
	| LC    | baubles                  | 1.5.2                     | Baubles-1.12-1.5.2.jar                                    | None                                     |
	| LC    | betterbuilderswands      | 0.11.1                    | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar           | None                                     |
	| LC    | bookshelf                | 2.3.590                   | Bookshelf-1.12.2-2.3.590.jar                              | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | forgelin                 | 1.8.4                     | Forgelin-1.8.4.jar                                        | None                                     |
	| LC    | bountiful                | 2.2.3                     | Bountiful-1.12.2-2.2.3.jar                                | None                                     |
	| LC    | chameleon                | 1.12-4.1.3                | Chameleon-1.12-4.1.3.jar                                  | None                                     |
	| LC    | chisel                   | MC1.12.2-1.0.2.45         | Chisel-MC1.12.2-1.0.2.45.jar                              | None                                     |
	| LC    | chiselsandbits           | 14.33                     | chiselsandbits-14.33.jar                                  | None                                     |
	| LC    | chunkgenlimit            | 1.1                       | chunkgenlimiter-1.1.jar                                   | None                                     |
	| LC    | collective               | 3.0                       | collective-1.12.2-3.0.jar                                 | None                                     |
	| LC    | comforts                 | 1.4.1.3                   | comforts-1.12.2-1.4.1.3.jar                               | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LC    | contenttweaker           | 1.12.2-4.10.0             | ContentTweaker-1.12.2-4.10.0.jar                          | None                                     |
	| LC    | crafttweakerjei          | 2.0.3                     | CraftTweaker2-1.12-4.1.20.687.jar                         | None                                     |
	| LC    | creativecore             | 1.10.0                    | CreativeCore_v1.10.70_mc1.12.2.jar                        | None                                     |
	| LC    | culinaryconstruct        | 1.3.4                     | culinaryconstruct-1.3.4.jar                               | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LC    | cxlibrary                | 1.6.1                     | cxlibrary-1.12.1-1.6.1.jar                                | None                                     |
	| LC    | cyberware                | 0.2.11.29                 | cyberware-1.12.2-0.2.11.29.jar                            | None                                     |
	| LC    | gamestages               | 2.0.123                   | GameStages-1.12.2-2.0.123.jar                             | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | dimstages                | 2.0.23                    | DimensionStages-1.12.2-2.0.23.jar                         | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | fantasticlib             | 1.12.2.047                | FantasticLib-1.12.2.047.jar                               | None                                     |
	| LC    | dynamicstealth           | 1.12.2.114                | DynamicStealth-1.12.2.114.jar                             | None                                     |
	| LC    | konkrete                 | 1.6.0                     | konkrete_forge_1.6.0_MC_1.12-1.12.2.jar                   | None                                     |
	| L     | fancymenu                | 2.14.7                    | fancymenu_forge_2.14.7_MC_1.12-1.12.2.jar                 | None                                     |
	| L     | ftbbackups               | 1.1.0.1                   | FTBBackups-1.1.0.1.jar                                    | None                                     |
	| L     | ftblib                   | 5.4.7.2                   | FTBLib-5.4.7.2.jar                                        | None                                     |
	| L     | ftbutilities             | 5.4.1.131                 | FTBUtilities-5.4.1.131.jar                                | None                                     |
	| L     | itemfilters              | 1.0.4.2                   | ItemFilters-1.0.4.2.jar                                   | None                                     |
	| L     | ftbquests                | 1202.9.0.15               | FTBQuests-1202.9.0.15.jar                                 | None                                     |
	| L     | waila                    | 1.8.26                    | Hwyla-1.8.26-B41_1.12.2.jar                               | None                                     |
	| L     | iblis_headshots          | 1.2.6                     | iblis-headshots-1.2.6.jar                                 | None                                     |
	| L     | ichunutil                | 7.2.2                     | iChunUtil-1.12.2-7.2.2.jar                                | None                                     |
	| L     | initialinventory         | 2.0.2                     | InitialInventory-3.0.0.jar                                | None                                     |
	| L     | inventorysorter          | 1.13.3+57                 | inventorysorter-1.12.2-1.13.3+57.jar                      | None                                     |
	| L     | ironchest                | 1.12.2-7.0.67.844         | ironchest-1.12.2-7.0.72.847.jar                           | None                                     |
	| L     | journeymap               | 1.12.2-5.7.1              | journeymap-1.12.2-5.7.1.jar                               | None                                     |
	| L     | justenoughdimensions     | 1.6.0-dev.20200416.184714 | justenoughdimensions-1.12.2-1.6.0-dev.20200416.184714.jar | None                                     |
	| L     | lootbags                 | 2.5.8.5                   | LootBags-1.12.2-2.5.8.5.jar                               | None                                     |
	| L     | loottweaker              | 0.3.1                     | LootTweaker-0.3.1+MC1.12.2.jar                            | None                                     |
	| L     | lostcities               | 2.0.22                    | lostcities-1.12-2.0.22.jar                                | None                                     |
	| L     | lostsouls                | 1.1.4                     | lostsouls-1.12-1.1.4.jar                                  | None                                     |
	| L     | lunatriuscore            | 1.2.0.42                  | LunatriusCore-1.12.2-1.2.0.42-universal.jar               | None                                     |
	| L     | materialchanger          | 1.0                       | materialchanger1.0.3-1.12.2.jar                           | None                                     |
	| L     | mobsunscreen             | @version@                 | mobsunscreen-1.12.2-3.1.5.jar                             | None                                     |
	| L     | morefurnaces             | 1.10.5                    | MoreFurnaces-1.12.2-1.10.6.jar                            | None                                     |
	| L     | supermartijn642configlib | 1.1.6                     | supermartijn642configlib-1.1.6-forge-mc1.12.jar           | None                                     |
	| L     | supermartijn642corelib   | 1.1.7                     | supermartijn642corelib-1.1.7-forge-mc1.12.jar             | None                                     |
	| L     | movingelevators          | 1.4.1                     | movingelevators-1.4.1-forge-mc1.12.jar                    | None                                     |
	| L     | multiblocked             | 0.8.0                     | multiblocked-0.8.0.jar                                    | None                                     |
	| L     | mw                       | 0.7.1                     | mw3.0_sqr-0.7.21 BETA_mc1.12.2.jar                        | None                                     |
	| L     | msic                     | 1.0                       | MyServerIsCompatible-1.12.2-1.0.jar                       | None                                     |
	| L     | oreexcavation            | 1.4.150                   | OreExcavation-1.4.150.jar                                 | None                                     |
	| L     | playerrevive             | 1.0                       | PlayerRevive_v1.2.40_mc1.12.2.jar                         | None                                     |
	| L     | srparasites              | 1.9.12                    | SRParasites-1.12.2v1.9.12.jar                             | None                                     |
	| L     | overlast                 | 0.2.8                     | overlast-1.12.2-0.2.8B3.jar                               | None                                     |
	| L     | patchouli                | 1.0-23.6                  | Patchouli-1.0-23.6.jar                                    | None                                     |
	| L     | purifiedfleshmod         | 1.0.0                     | purifiedflesh_1.0.1_1.12.2.jar                            | None                                     |
	| L     | quarkoddities            | 1                         | QuarkOddities-1.12.2.jar                                  | None                                     |
	| L     | randomtweaks             | 1.12.2-2.8.3.1            | randomtweaks-1.12.2-2.8.3.1.jar                           | None                                     |
	| L     | rewired                  | 1.12.2                    | ReWIRED-1.0.9b.jar                                        | None                                     |
	| L     | sereneseasons            | 1.2.18                    | SereneSeasons-1.12.2-1.2.18-universal.jar                 | None                                     |
	| L     | spawnercontrol           | 1.6.3b                    | SpawnerControl-1.6.3b.jar                                 | None                                     |
	| L     | storagedrawers           | 5.2.2                     | StorageDrawers-1.12.2-5.4.2.jar                           | None                                     |
	| L     | surge                    | 2.0.77                    | Surge-1.12.2-2.0.77.jar                                   | None                                     |
	| L     | sync                     | 7.1.0                     | Sync-1.12.2-7.1.0.jar                                     | None                                     |
	| L     | toolbelt                 | 1.9.14                    | ToolBelt-1.12.2-1.9.14.jar                                | None                                     |
	| L     | treeharvester            | 4.0                       | treeharvester_1.12.2-4.0.jar                              | None                                     |
	| L     | walljump                 | 1.3.2                     | walljump-1.12.2-1.3.2.jar                                 | None                                     |
	| L     | wumpleutil               | 2.12.9                    | wumpleutil-1.12.2-2.12.9.jar                              | None                                     |
	| L     | webslinger               | 2.2.4                     | webslinger-1.12.2-2.2.4.jar                               | None                                     |
	| L     | zensummoning             | 1.1.0                     | Zen Summoning-1.12-1.1.0.jar                              | None                                     |
	| L     | zenutils                 | 1.13.5                    | zenutils-1.13.5.jar                                       | None                                     |
	| L     | immersiveengineering     | 0.12-98                   | ImmersiveEngineering-0.12-98.jar                          | None                                     |
	| L     | jade                     | 0.1.0                     | Jade-0.1.0.jar                                            | None                                     |

	Loaded coremods (and transformers): 
FMCore (fancymenu_forge_2.14.7_MC_1.12-1.12.2.jar)
  
IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  cubex2.cxlibrary.CoreModTransformer
Quark Plugin (Quark-r1.6-179.jar)
  vazkii.quark.base.asm.ClassTransformer
AppleCore (AppleCore-mc1.12.2-3.4.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
Moving Elevators Plugin (movingelevators-1.4.1-forge-mc1.12.jar)
  
ChunkGenLimiterCoremod (chunkgenlimiter-1.1-core.jar)
  io.github.barteks2x.chunkgenlimiter.coremod.ChunkGenLimitTransformer
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
JechCore (jecharacters-1.12.0-3.7.1.jar)
  me.towdium.jecharacters.core.JechClassTransformer
SurgeLoadingPlugin (Surge-1.12.2-2.0.77.jar)
  
KonkreteCore (konkrete_forge_1.6.0_MC_1.12-1.12.2.jar)
  
MixinBooter (!mixinbooter-7.1.jar)
  
MSICCoreMod (MyServerIsCompatible-1.12.2-1.0.jar)
  
RandomPatches (randompatches-1.12.2-1.22.1.10.jar)
  com.therandomlabs.randompatches.core.RPTransformer
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
CreativePatchingLoader (CreativeCore_v1.10.70_mc1.12.2.jar)
  
B3M_CorePlugin (B3M-1.12.2-17.jar)
  sedridor.B3M.core.B3M_Transformer
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
CoreMod (MiniEffects-1.12.2-1.1.0.jar)
  
weaponlib (mw3.0_sqr-0.7.21 BETA_mc1.12.2.jar)
  com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer
SuperMartijn642's Core Lib Plugin (supermartijn642corelib-1.1.7-forge-mc1.12.jar)
  
CorePlugin (ForgeEndertech-1.12.2-4.5.6.1-build.0648.jar)
  
MultiblockedLoadingPlugin (multiblocked-0.8.0.jar)
  com.cleanroommc.multiblocked.core.ASMTransformer
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

### 问题描述 (Bug Description)

开服务器报错

**Comment by yhwsndbb** [comment]
我以为就我一个人是这样的，我这也是，请问你现在解决了吗

**Comment by GFHK416** [comment]
> 我以为就我一个人是这样的，我这也是，请问你现在解决了吗

没

**Comment by PIPILAN** [comment]
https://github.com/PIPILAN/Parasites-Blood-Dawn/issues/21
