### ISSUE TITLE
维克3.0霞弹枪械弹夹异常清空

### ISSUE THREAD

**Issue by Mylifenew** [PIPILAN/Parasites-Blood-Dawn#24]
### 是否有增添模组或者修改配置文件？ (Are there any modules added or configuration files modified?)

是

### 整合包版本 (Modpack Version)

1.1.1

### Java

1.8.0

### 问题描述 (Bug Description)

开枪时一整个弹夹都会清空，哪怕射出去的只有一颗子弹，弹夹的子弹也消失了，就等于一个弹夹容量只能打一枪；目前只测试了其它的，单玩则不会

**Comment by PIPILAN** [comment]
维克枪械模组问题，无力修复
