### ISSUE TITLE
服务器创建异常

### ISSUE THREAD

**Issue by Fillingcompleted** [PIPILAN/Parasites-Blood-Dawn#25]
### 是否有增添模组或者修改配置文件？ (Are there any modules added or configuration files modified?)

是

### 整合包版本 (Modpack Version)

1.1.1

### Java

1.8.0_192

### 崩溃报告 (Crash Report)

[latest.log](https://github.com/PIPILAN/Parasites-Blood-Dawn/files/11998143/latest.log)

### 问题描述 (Bug Description)

按照流程安装并启动服务端后，服务器无法生成整合包地形，并且出现了模组内容缺失等问题

**Comment by PIPILAN** [comment]
记录中并无任何模组启动，猜测为启动参数设置错误，启动了原版的服务端，请自行检查
