### ISSUE TITLE
有没有考虑加入遗体mod

### ISSUE THREAD

**Issue by MicroNeutron** [PIPILAN/Parasites-Blood-Dawn#27]
### 评分 Rate

1/10

### 目前痛点 (Current Problems)

我看到wiki上说墓碑在掉落上有一些bug，而且可能死亡原地生成墓碑不是那么“现实”的想法

### 您的想法 (Your Thoughts)

可以试试用遗体mod替换掉墓碑mod来解决这个bug，而且死后生成遗体也比生成墓碑可能更加符合世界观一些

**Comment by PIPILAN** [comment]
无论是哪个遗体模组或者墓碑模组，测试都不兼容维克的背包，大概率是因为维克闭源，所以干脆就没加，直接用的夸克奇思妙想的图腾。图腾也不会被卡没，墓碑之前有人反馈被卡掉炸掉。尸体忘记什么问题了，反正也不行。既然作用相同，索性用了个bug更少更稳定的图腾
