### ISSUE TITLE
游戏文件已下载完成，在启动时出现问题直接崩溃，html和pcl都不可启动

### ISSUE THREAD

**Issue by shou114514** [PIPILAN/Parasites-Blood-Dawn#5]
[minecraft-exported-crash-info-2022-05-25T11-48-28.zip](https://github.com/PIPILAN/Parasites-Blood-Dawn/files/8767763/minecraft-exported-crash-info-2022-05-25T11-48-28.zip)

**Comment by PIPILAN** [comment]
尝试把JAVA更新到8u333版本试试，我看到liteloader貌似炸了

**Comment by shou114514** [comment]
好的，我去试一下

**Comment by shou114514** [comment]
下载后的java仍然不能启动游
[错误报告-2022-5-25_12.14.08.zip](https://github.com/PIPILAN/Parasites-Blood-Dawn/files/8767862/-2022-5-25_12.14.08.zip)
戏

**Comment by PIPILAN** [comment]
> 下载后的java仍然不能启动游 [错误报告-2022-5-25_12.14.08.zip](https://github.com/PIPILAN/Parasites-Blood-Dawn/files/8767862/-2022-5-25_12.14.08.zip) 戏

整合包中并无liteloader相关模组，是否自行添加了模组？
