### ISSUE TITLE
打开商店时闪退

### ISSUE THREAD

**Issue by Rain073** [PIPILAN/Parasites-Blood-Dawn#6]
[crash-2022-05-28_09.03.57-client.txt](https://github.com/PIPILAN/Parasites-Blood-Dawn/files/8790230/crash-2022-05-28_09.03.57-client.txt)
[minecraft-exported-crash-info-2022-05-28T09-07-20.zip](https://github.com/PIPILAN/Parasites-Blood-Dawn/files/8790231/minecraft-exported-crash-info-2022-05-28T09-07-20.zip)

**Comment by Rain073** [comment]
> 请使用windows系统开服，adminshop模组只支持GB2312编码，默认使用UTF-8的linux系统无法开服（包括面板服）

谢谢！在将LANG设置为zh_CN.GBK后游戏正常。

**Comment by SQwatermark** [comment]
我制作了adminshop的修改版本，强制使用utf-8编码（对于mc来说这是标准编码），已在Windows和Linux进行测试。
使用该版本需要将shop.csv转换为utf-8编码
下载地址：https://github.com/SQwatermark/AdminShop/releases/tag/release

**Comment by PIPILAN** [comment]
> 我制作了adminshop的修改版本，强制使用utf-8编码（对于mc来说这是标准编码），已在Windows和Linux进行测试。 使用该版本需要将shop.csv转换为utf-8编码 下载地址：https://github.com/SQwatermark/AdminShop/releases/tag/release

可以尝试联系原作者请求授权，如果能拿到授权上传到curseforge我就可以更新到整合包中，不然我无法将其更入整合包。
