### ISSUE TITLE
跑着跑着就闪退

### ISSUE THREAD

**Issue by yuanchi0828** [PIPILAN/Parasites-Blood-Dawn#7]
### 校验 (Check)

否

### 整合包版本 (Modpack Version)

1.12.2

### Java

Java8 64位

### 崩溃报告 (Crash Report)

[错误报告-2022-6-3_16.18.58.zip](https://github.com/PIPILAN/Parasites-Blood-Dawn/files/8830793/-2022-6-3_16.18.58.zip)

### 问题描述 (Bug Description)

跑着跑着就闪退了，然后就进不去了，我已经遇见了5 6 次了，心态崩了，求求大佬解答一下，是哪里出问题了

**Comment by PIPILAN** [comment]
此问题还在定位测试中

**Comment by yuanchi0828** [comment]
OK，知道了

**Comment by yuanchi0828** [comment]
心疼我的档

**Comment by PIPILAN** [comment]
#12 此问题已找到原因，并且我在foodfunk的开源仓库中发现了类似问题，基本定位到此模组，下版本会移除尝试修复。

**Comment by PIPILAN** [comment]
已修复 https://github.com/PIPILAN/Parasites-Blood-Dawn/commit/72a6ea71df329dbd515758dbea40b79f3bcffa7f
