### ISSUE TITLE
使用坐标点传送后崩溃，然后再也进不去

### ISSUE THREAD

**Issue by bixiyi** [PIPILAN/Parasites-Blood-Dawn#8]
### 校验 (Check)

否

### 整合包版本 (Modpack Version)

1.0.4.2

### Java

8u333

### 崩溃报告 (Crash Report)

[错误报告-2022-6-4_10.20.13.zip](https://github.com/PIPILAN/Parasites-Blood-Dawn/files/8836688/-2022-6-4_10.20.13.zip)

### 问题描述 (Bug Description)

[错误报告-2022-6-4_10.20.13.zip](https://github.com/PIPILAN/Parasites-Blood-Dawn/files/8836814/-2022-6-4_10.20.13.zip)

**Comment by PIPILAN** [comment]
#7 等待修复
