### ISSUE TITLE
今天玩了一会结果游戏崩了，模组我就加了个连锁

### ISSUE THREAD

**Issue by hhhhhweqwew** [PIPILAN/Parasites-Blood-Dawn#9]
### 是否有增添模组或者修改配置文件？ (Are there any modules added or configuration files modified?)

否

### 整合包版本 (Modpack Version)

1.0

### Java

8.0.291

### 崩溃报告 (Crash Report)

[错误报告-2022-6-6_17.00.01.zip](https://github.com/PIPILAN/Parasites-Blood-Dawn/files/8843629/-2022-6-6_17.00.01.zip)

### 问题描述 (Bug Description)

![QQ截图20220606171822](https://user-images.githubusercontent.com/106959902/172139926-f3e6ba4f-50b4-453d-806e-34ff7d2e6552.png)

**Comment by PIPILAN** [comment]
首先整合包版本写的不对，其次此问题会在下版本解决

**Comment by hhhhhweqwew** [comment]
整合包版本在哪看

**Comment by hhhhhweqwew** [comment]
> 首先整合包版本写的不对，其次此问题会在下版本解决

整合包版本在哪看

**Comment by PIPILAN** [comment]
> 

游戏启动后主界面左下角

**Comment by hhhhhweqwew** [comment]
> > 
> 
> 游戏启动后主界面左下角

1.0.4.2

**Comment by hhhhhweqwew** [comment]
> 首先整合包版本写的不对，其次此问题会在下版本解决

其次此问题会在下版本解决是指下一次更新解决吗
